version: '3'
services:
    
    pgdb:
        image: postgres:9.6.22-stretch
        environment: 
            - POSTGRES_PASSWORD=qaninja
        ports: 
            - "5432:5432"
        networks:
            - skynet

    pgadmin:
        image: dpage/pgadmin4:5.4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=root@qaninja.io
            - PGADMIN_DEFAULT_PASSWORD=qaninja
        ports: 
            - "15432:80"
        networks: 
            - skynet
        depends_on: 
            - "pgdb"
    
    ninjaplus-api:
        image: qaninja/ninjaplus-api
        environment: 
            - DATABASE=pgdb
        ports: 
            - "3000:3000"
        networks: 
            - skynet
        depends_on: 
            - "pgadmin"

    ninjaplus-web:
        image: qaninja/ninjaplus-web
        environment: 
            - VUE_APP_API=http://ambientehomol_ninjaplus-api_1:3000
        ports: 
            - "5000:5000"
        networks: 
            - skynet

networks: 
    skynet:
        driver: bridge